# Generated by Django 3.1 on 2020-10-06 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MessageChat',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('message_user', models.CharField(max_length=2048)),
                ('date_send_message', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='let.user')),
            ],
        ),
    ]
